### PR TITLE
feat(eval): Add eval by blocks, stop evaluation early if it failed, make REPLSmuggler.jl compatible with OhMyREPL.jl

### PR DESCRIPTION
**Pull request by ArbitRandomUser**
This is a work in progress , 
Do give it a shot and let me know what you think

Ive (temporarily) renamed your implementation of `evaluate_entry` to `evaluate_entry_old` and added my own `evaluate_entry` .

The new `evaluate_entry` sends multiple lines to the repl and executes them together instead of line by line in the repl . This is to address #28 .

Also hey! now OhMyREPL highlighting works on smuggled code \o/ !!

It seems this way of doing also tackles the "paste" behavior mentioned in this discourse post 
https://discourse.julialang.org/t/ann-replsmuggler-jl-send-code-to-your-julia-repl-and-get-neo-vim-diagnostics-in-return/111420/2?u=arbitrandomuser

this is a work in progress , i still haven't looked at the protocol and nvim to switch between old and new behaviour based on some config. For now smuggling should execute  the new behaviour .

I ran tests and they pass on my machine

### CODE REVIEW

**Comment by Klafyvel** [comment]
Nice, thank you for your contribution. I was looking at julia-repl-vim this afternoon and I liked the simpler way they parsed stuff. 

Now, some issues with your proposed solution.
- Syntax errors are reported only at the end of the evaluated block, which prevents locating them correctly in the original file (you can test that by evaluating the 12 first lines of the test file I've linked below; the syntax error is reported on line 12).
- The history is managed right away by `Base.REPL` with the use of `commit_line`, which is super nice! this means we can remove that part from REPLSmuggler. However, if the user is currently searching in the history (for example, press the arrow up and then try to send a bunch of code), the session will crash badly. You can probably fix that by simply checking that the REPL is in the proper state.
- The evaluated code is committed as a single block in the history, which removes a bit of the purpose of history. I think It'be more useful if we could commit single top-level expressions instead, as was done before. For that purpose, maybe you could re-use the old function, committing each expression before evaluation but stopping the loop as soon as an error is raised? Moreover, now that I think of it, I do not believe that we need to change the protocol if we do it that way. It simply makes sense to stop evaluation early if an error occurs.


Here's [the file I usually use for testing REPLSmuggler.jl](https://gist.github.com/Klafyvel/65a39cd099c4c8fb8612c1b5877b305d), I should turn it into proper unit tests, but that's not super easy to do (currently, the unit tests only test the protocol).

Tell me if you need, or want a hand, I can do these modifications if needed.

**Comment by ArbitRandomUser** [comment]
i'm a little confused regarding point number 1.  it'd be great to have it show the error on line 5 over line 12 , but it seems like the current behaviour too reports the error on line 12 

this is the output when i am on `main` 
fig

which seems to make sense since if i paste the following into the repl , the parser reports the error on line 8 in this snippet.

fig

**Comment by Klafyvel** [comment]
Yes indeed, it seems it comes from the parser, so my first point should be
ignored.

**Comment by ArbitRandomUser** [comment]
as for point 3 ,
it comes down to a personal preference .
If i submitted a block of code , its likely i want to run that block of code again and it'd be nice if i simply ctrl-p 'd to that block in history and hit enter.

this is also the default behavior in the julia repl.
```julia
a=1 #hit alt-enter
a=2
```
the above snippet is saved in history as is , and going back through history brings it up as a block and not cycling through `a=2` then `a=1` .

If you aren't convinced I dont mind implementing it the way you have suggested. Do let me know your thoughts on this

**Comment by Klafyvel** [comment]
hum, I did not consider this as I thought it was only a question of stopping the evaluation early. Maybe it is good to put it as an option in the protocol (evaluation by block or evaluation by statement), as I think my personal preference goes to the evaluation by statement, but your approach is completely valid as well. It might be time to add a configuration method to [the protocol](https://klafyvel.github.io/REPLSmuggler.jl/dev/#Protocol). For now, it only needs to be able to set the evaluation method, but in the future, it can hold other stuff, such as the name of the module in which the evaluation should take place. 

For the second point, I started experimenting last night (see https://github.com/Klafyvel/REPLSmuggler.jl/commit/7ef7c0287dde9bd8cc596a908bfc25a6e753c35e), but I'm not sure I understand correctly how to switch modes in the Julia REPL.

**Comment by ArbitRandomUser** [comment]
are you expecting it to be back in the same position in history when you the transition after the loop runs here?
https://github.com/Klafyvel/REPLSmuggler.jl/blob/7ef7c0287dde9bd8cc596a908bfc25a6e753c35e/src/eval.jl#L76 

you might have to restore to the same point in history with `history_move_prefix` specifying the `cur_idx`
(im as speculative as you are on this , I really dont grok the REPL codebase fully)

https://github.com/JuliaLang/julia/blob/996351f5f6651d1508aef3c35c7d37eb22a0fb1e/stdlib/REPL/src/REPL.jl#L1024

**Comment by Klafyvel** [comment]
I added this because I thought it would get me back to the state the REPL was before code evaluation, but I think it's not great: code evaluation should simply cancel the current history search if one is running. The thing is before I added that line, the REPL would be in an undefined state after evaluation causing errors if you hit Ctrl+D to leave the REPL for example. Perhaps there is no universalway to go back to the simple `:julia` repl state, and we should act differently depending on what is the current state. For example: 
- https://github.com/JuliaLang/julia/blob/996351f5f6651d1508aef3c35c7d37eb22a0fb1e/stdlib/REPL/src/REPL.jl#L1189
- https://github.com/JuliaLang/julia/blob/996351f5f6651d1508aef3c35c7d37eb22a0fb1e/stdlib/REPL/src/LineEdit.jl#L2555
- https://github.com/JuliaLang/julia/blob/996351f5f6651d1508aef3c35c7d37eb22a0fb1e/stdlib/REPL/src/LineEdit.jl#L2266

(I wish the REPL was a bit more documented, or had a public API to hook into :( )

**Comment by ArbitRandomUser** [comment]
could you check once more if its being commited to history ,
i think i might have made a mistake and been thinking its commited to history because i was esentially re running the same bits of code over again.

**Comment by Klafyvel** [comment]
I'll have a look at it tonight, maybe it's also time that I add some proper tests. Could you allow maintainers to edit your Pull Request? (there should be a box that you can tick somewhere on the interface) That way I can add stuff to your work.

I've also asked for some help on the #repl channel on slack.

**Comment by ArbitRandomUser** [comment]
i have enable maintainers to edit the PR

**Comment by ArbitRandomUser** [comment]
right now , after after smuggling code the new prompt immediately follows the previous prompt unlike typing in the repl

its a cosmetic change , but personally i feel this makes it looked a little cramped, especially when visually scanning and inspecting the outputs.

**Comment by Klafyvel** [comment]
Indeed, I'll fix it once I'm done with nvim-smuggler.

**Comment by ArbitRandomUser** [comment]
Another suggestion , is the loclist really needed now that it stops execution on first error there will only be 1 location ?

the user experience would be better if they didnt have to dismiss the location list every time

**Comment by Klafyvel** [comment]
Okay! I'm happy with that for now, which means it's time to stop. Let's see if it still looks good tomorrow and then it can be merged.

**Comment by ArbitRandomUser** [comment]
Tested it out a bit , works great so far \o/ . Thanks a lot :)

As for the loclist , i think it can remain even though only 1 error will be reported as its one keystroke(Enter) to move to the error

i have added autocommands in my vimrc to dismiss the loclist 

```
"close loclist on selection
autocmd FileType qf nmap <buffer> <cr> <cr>:lcl<cr>
"close loclist on escape
autocmd FileType qf nmap <buffer> <esc> :lcl<cr> 
```

**Comment by Klafyvel** [comment]
The loclist can actually have multiple entries if you start having nested code, which makes it sometimes useful. But I agree that currently, it's often annoying. I'll open a new issue in nvim-smuggler to make it optional by default.

**Pull request merged**
